services:
  inventory-postgres:
    image: postgres:16
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventory_service_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "5433:5432"        # host:5432 -> container:5432
    volumes:
      - inventory_pg_data:/var/lib/postgresql/data

volumes:
  inventory_pg_data:
